#!/usr/bin/env bash
sudo pacman -Syu

sudo pacman -S --noconfirm \
    base-devel \
    network-manager-applet \
    gnome-themes-extra gtk3 lxappearance \
    blueman bluez bluez-utils \
    alsa-lib alsa-firmware alsa-utils pavucontrol pipewire pipewire-audio pipewire-pulse \
    ttf-cascadia-mono-nerd ttf-dejavu ttf-liberation ttf-nerd-fonts-symbols-mono noto-fonts-emoji noto-fonts-cjk \
	git tmux alacritty neovim github-cli openssh \
	nodejs npm \
	python3 python-pip python-virtualenv \
	gcc \
	feh vlc \
	copyq xclip \
	gparted \
	ripgrep \
	gnome-calendar gnome-calculator  \
	libreoffice-fresh \
	tldr neofetch btop fzf bat \
	nemo \
	redshift \
	flameshot \
	xcape \
	rofi \
	polybar \
	picom \
	mangohud \
	keepassxc \
    dunst \
    cheese \
    thunderbird discord steam spotify-launcher \
