#!/usr/bin/env bash
sudo pacman -Syu

sudo pacman -S --noconfirm \
    base-devel \
    grub os-prober efibootmgr \
    network-manager-applet \
    gnome-themes-extra gtk3 lxappearance \
    blueman bluez bluez-utils \
    alsa-lib alsa-firmware alsa-utils pavucontrol pipewire pipewire-audio pipewire-pulse \
    ttf-cascadia-mono-nerd ttf-dejavu ttf-liberation ttf-nerd-fonts-symbols-mono noto-fonts-emoji noto-fonts-cjk \
	git tmux alacritty neovim github-cli openssh \
	nodejs npm \
	python3 python-pip python-virtualenv \
	gcc \
    stow \
	feh vlc \
	copyq xclip \
	gparted \
	ripgrep \
	libreoffice-fresh \
	tldr neofetch btop fzf bat jq \
	nemo \
	redshift \
	flameshot \
    calcurse \
	xcape \
	i3-wm i3lock rofi polybar xss-lock xautolock \
    tmux \
    neovim \
    zsh \
	picom \
	mangohud \
	keepassxc \
    dunst \
    cheese \
    thunderbird steam \
    obs-studio \
